### ISSUE TITLE
传输的文件到哪里去了，要怎么下载呢

### ISSUE THREAD

**Issue by Antisunny** [WCY-dt/EasyTransfer#38]
尝试使用macOS和android传输文件，双向传输文件都进度条都满了，但不知道文件去哪里了？或者要怎么下载？？

**Comment by WCY-dt** [comment]
直接点击那个文件就好了！

感谢您提出疑惑，我后面会考虑优化一下移动端的操作逻辑 :)

**Comment by chenqiwei123** [comment]
不太行，最好那个码能绑定设备，一刷新就换了。兼容下移动端

**Comment by WCY-dt** [comment]
> 不太行，最好那个码能绑定设备，一刷新就换了。兼容下移动端
> 

绑定设备很好实现，但我的想法是尽量去满足匿名性，所以设计成了刷新就生成新的设备码

**Comment by Antisunny** [comment]
除了移动设备，例如我在PICO VR设备中，只有click和long click，没有右键。希望可以双击复制文本，下载文件的话，可以长按，thx。

**Comment by WCY-dt** [comment]
> 除了移动设备，例如我在PICO VR设备中，只有click和long click，没有右键。希望可以双击复制文本，下载文件的话，可以长按，thx。

您好，我已经添加了复制和下载的按钮，现在只需要点击即可。我在移动设备上测试正常，但我没有 VR 设备，请问可以帮我试一下能否正常使用吗？非常感谢！

**Comment by WCY-dt** [comment]
> 测试了Pico4 VR，是部分可用的
> 
> |发送|接受|结果|
> |--|--|--|
> |VR 文字|Windows|✅|
> |VR 图片|Windows|✅|
> |Windows 文字|VR|✅|
> |Windows 图片|VR|✅|
> |VR|Windows .exe 14Mb|一直显示蓝色，无法下载。<br/>$${\color{red}会导致后续的所有文字、图片、文件传输都变成蓝色，无法完成}$$|
> |Windows .apk 34Mb|VR|一直显示蓝色，无法下载。<br/>$${\color{red}会导致后续的所有文字、图片、文件传输都变成蓝色，无法完成}$$|
> 
> ![Windows端无法接收](https://github.com/user-attachments/assets/e064871d-2e19-42ca-9a81-072a5f611a4f)


非常非常非常感谢！我会尽快修复这些问题！

**Comment by WCY-dt** [comment]
根据我在本地的测试，传输出错的主要原因是网络波动导致的丢包。而如果前一个文件没有传输成功，后面的文件会被阻塞。

由于我目前的 STUN/TURN 服务器均在境外，丢包的概率还是存在的，所以我现在将最大重传次数改为了 10，尽量减少丢包。

当然，最好的方法还是在境内自行部署 STUN/TURN 服务器，但这可能存在监管问题。
