### ISSUE TITLE
演示站点无法使用

### ISSUE THREAD

**Issue by iamobj** [WCY-dt/EasyTransfer#43]
刚跟朋友试了下，无法通信，能显示对方的 code，但是按钮都是灰色禁用。
![1734681573213](https://github.com/user-attachments/assets/4ced2ebc-6b7f-4840-b4eb-2bc84b91c545)
自己用不同的浏览器试了下可以通，好像只能局域网用

**Comment by WCY-dt** [comment]
您好，感谢关注与反馈！

根据您的截图和服务器记录的有限数据，两台设备已经通过信令服务器成功交换了信息，但是无法建立端到端连接。

这可能有以下几个原因：

1. 某台设备在局域网中，而该局域网的策略禁止了 WebRTC 进行的内网穿透；
2. 我目前的 STUN/TURN 服务器部署在境外，偶尔网络环境抽风，需要挂代理访问；

这两者都由客观情况决定，暂时无法通过修改代码解决。您可以试着在两台设备都刷新页面后重新连接试试。

**Comment by iamobj** [comment]
好的，感谢你的回复和答疑

**Comment by WCY-dt** [comment]
你好，debug发现确实是STUN/TURN服务器的问题，部分地址无法联通。我已经将STUN/TURN服务器切换为了更好的版本，现在应该不会再连不上了，而且速度应该也提升了。

**Comment by WCY-dt** [comment]
STUN/TURN服务器在国内不太合规，境外自己建的话流量费用较高，作为一个免费的开源项目不太负担得起。所以现在只能找靠谱的服务去用它们的免费额度，这也算是个折衷的办法了。
